#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin");

reader.fill(writeMore);

function writeMore(error) {
  if (error) throw error;
  var data = reader.read();

  if (data) process.stdout.write(data);

  if (reader.ended) return;

  reader.fill(writeMore);
}
