#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout");

reader.fill(function drain(error) {
  if (error) throw error;
  var data = reader.read();
  if (data && !writer.write(data)) return writer.drain(drain);
  if (reader.ended) return writer.end();
  reader.fill(drain);
});
