#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout");

reader.fill(function pipe(error) {
  if (error) throw error;
  writer.write(reader.read());
  if (reader.ended) writer.end(function(error) { if (error) throw error; });
  else writer.flush(function(error) { if (error) throw error; reader.fill(pipe); });
});
