#!/usr/bin/env node

var rw = require("../");

var reader = rw.reader(process.argv[2] || "/dev/stdin");

reader.fill(function pipe(error) {
  if (error) throw error;
  if (reader.available) process.stdout.write(reader.read());
  if (!reader.ended) reader.fill(pipe);
});
