#!/usr/bin/env node

var rw = require("../");

var readFixed = rw.fixedReader(process.argv[2] || "/dev/stdin");

(function readNextChunk() {
  readFixed(10, function(error, chunk) {
    if (error) throw error;
    if (chunk == null) return;
    process.stdout.write(chunk);
    setTimeout(readNextChunk, 100);
  });
})();
