#!/usr/bin/env node

// var rw = require("../");

// var readLine = rw.lineReader(process.argv[2] || "/dev/stdin");

// (function readNextLine() {
//   readLine(function(error, line) {
//     if (error) throw error;
//     if (line == null) return;
//     console.log(line);
//     setImmediate(readNextLine);
//   });
// })();
