#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout");

reader.fill(filled);

function filled(error) {
  if (error) throw error;
  writer.write(reader.read());
  if (reader.ended) writer.end(ended);
  else writer.drain(drained);
}

function drained(error) {
  if (error) throw error;
  reader.fill(filled);
}

function ended(error) {
  if (error) throw error;
}
