#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout");

reader.fill(filled);

function filled(error) {
  if (error) throw error;
  var record;

  while ((record = reader.read(10)) != null) {
    if (writer.write(record) == null) { // TODO if this fails, we need to rewrite this record!
      return writer.flush(filled);
    }
  }

  if (reader.ended) writer.end(ended);
  else writer.flush(flushed);
}

function flushed(error) {
  if (error) throw error;
  reader.fill(filled);
}

function ended(error) {
  if (error) throw error;
}
