#!/usr/bin/env node

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout");

reader.fill(function pipe(error) {
  if (error) throw error;
  var record;

  while ((record = reader.read(10)) != null) {
    if (!writer.write(record)) {
      return writer.drain(pipe);
    }
  }

  if (reader.ended) return writer.end();

  reader.fill(pipe);
});
