#!/usr/bin/env node

var rw = require("../");

var readLine = rw.lineReader(process.argv[2] || "/dev/stdin"),
    writeLine = rw.lineWriter("/dev/stdout");

(function pipeNextLine() {
  readLine(function(error, line) {
    if (error) throw error;
    writeLine(line, function(error) {
      if (error) throw error;
      if (line == null) return;
      setImmediate(pipeNextLine);
    });
  });
})();
