#!/usr/bin/env node

var rw = require("../");

var reader = rw.transformReader(rw.fileReader(process.argv[2] || "/dev/stdin"), rw.lineParser()),
    writer = rw.transformWriter(rw.fileWriter(process.argv[3] || "/dev/stdout"), rw.lineFormatter());

reader.fill(function flow(error) {
  if (error) throw error;
  var line;

  while ((line = reader.read(reader.ended)) != null) {
    if (!writer.write(line)) {
      return writer.drain(pipe);
    }
  }

  if (reader.ended) return writer.end();

  reader.fill(flow);
});
