#!/usr/bin/env node

var os = require("os");

var rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    parser = rw.lineParser().encoding("utf8"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout").encoding("utf8");

reader.fill(filled);

function filled(error) {
  if (error) throw error;
  parser.push(reader.read());
  pushed(null);
}

function pushed(error) {
  if (error) throw error;
  var line;

  while ((line = parser.pop(reader.ended)) != null) {
    if (writer.write(line + os.EOL) == null) { // TODO if this fails, we need to rewrite this line!
      return writer.flush(pushed);
    }
  }

  pulled(null);
}

function pulled(error) {
  if (error) throw error;
  if (reader.ended) writer.end(ended);
  else writer.flush(flushed);
}

function flushed(error) {
  if (error) throw error;
  reader.fill(filled);
}

function ended(error) {
  if (error) throw error;
}
