#!/usr/bin/env node

var os = require("os"),
    rw = require("../");

var reader = rw.fileReader(process.argv[2] || "/dev/stdin"),
    writer = rw.fileWriter(process.argv[3] || "/dev/stdout"),
    parser = rw.dsvParser();

reader.fill(drain);

function drain(error) {
  if (error) throw error;
  var data = reader.read(),
      row;

  if (data) parser.push(data);

  while ((row = parser.pop(reader.ended)) != null) {
    if (!writer.write(JSON.stringify(row) + os.EOL)) {
      return writer.drain(drain);
    }
  }

  if (reader.ended) return writer.end(end);

  reader.fill(drain);
}

function end(error) {
  if (error) throw error;
}
