#!/usr/bin/env node

var os = require("os"),
    rw = require("../");

var reader = rw.transformReader(rw.fileReader(process.argv[2] || "/dev/stdin").bufferLength(12), rw.dsvParser()),
    writer = rw.transformWriter(rw.fileWriter(process.argv[3] || "/dev/stdout"), rw.jsonFormatter());

reader.fill(function flow(error) {
  if (error) throw error;
  var row;

  while ((row = reader.read(reader.ended)) != null) {
    if (!writer.write(row)) {
      return writer.drain(pipe);
    }
  }

  if (reader.ended) return writer.end();

  reader.fill(flow);
});
